### PR TITLE
Will 7

### PR DESCRIPTION
**Pull request by WillHHH**

### CODE REVIEW

**Comment by chuxu200328** [comment]
image
Big gap next to the page.

**Comment by chuxu200328** [comment]
image
navbar hight wrong(too high)

**Comment by WillHHH** [comment]
fixed

**Comment by chuxu200328** [comment]
image
still has a big white blank next to the page

**Comment by WillHHH** [comment]
fixed

**Review by chuxu200328 — APPROVED** [review]
The overall work is good, but there are a lot of little issues, next time pay attention to details.

**Pull request merged**
